export interface Situation {
  id: number;
  name: string;
  imageUrl: string;
  roles: string[];
}

export const situations: Situation[] = [
  // --- 100 הסיטואציות המקוריות ---
  { id: 1, name: "בַּסּוּפֶּרְמַרְקֶט", imageUrl: "/locations/supermarket.webp", roles: ["קוֹפַאי", "לָקוֹחַ", "סַדָּר", "מְנַהֵל"] },
  { id: 2, name: "גַּן חַיּוֹת", imageUrl: "/locations/zoo.webp", roles: ["מְטַפֵּל", "וֶטֶרִינָר", "מְבַקֵּר", "שׁוֹמֵר"] },
  { id: 3, name: "מְסִבַּת יוֹמֻלֶּדֶת", imageUrl: "/locations/birthday_party.webp", roles: ["יֶלֶד יוֹמֻלֶּדֶת", "קוֹסֵם", "חָבֵר", "לֵיצָן"] },
  { id: 4, name: "מַעֲמַקֵּי הַיָּם", imageUrl: "/locations/deep_sea.webp", roles: ["צַלָּן", "מַדְּעָן", "נֶהָג צַלֶּלֶת", "צַלָּם"] },
  { id: 5, name: "תַּחֲנַת חָלָל", imageUrl: "/locations/space_station.webp", roles: ["אַסְטְרוֹנָאוּט", "מְפַקֵּד", "מַדְּעָן", "טֶכְנַאי"] },
  { id: 6, name: "בַּמִּרְפָּאָה", imageUrl: "/locations/clinic.webp", roles: ["רוֹפֵא", "חוֹלֶה", "אָחוֹת", "מַזְכִּירָה"] },
  { id: 7, name: "בַּקּוֹלְנוֹעַ", imageUrl: "/locations/cinema.webp", roles: ["סַדָּר", "צוֹפה", "מוֹכֵר פּוֹפְּקוֹרְן", "מַקְרִין"] },
  { id: 8, name: "בַּגִּנָּה הַצִּבּוּרִית", imageUrl: "/locations/public_park.webp", roles: ["יֶלֶד", "הַדּוֹדָה", "סָבְתָא", "שׁוֹמֵר"] },
  { id: 9, name: "בַּמִּטְבָּח", imageUrl: "/locations/kitchen.webp", roles: ["טַבָּח", "עוֹזֵר טַבָּח", "מַלְצַר", "שׁוֹטֵף כֵּלִים"] },
  { id: 10, name: "מִגְרַשׁ כַּדּוּרֶגֶל", imageUrl: "/locations/soccer_field.webp", roles: ["שַׂחְקָן", "שׁוֹפֵט", "מְאַמֵּן", "אוֹהֵד"] },
  { id: 11, name: "תַּחֲנַת כִּבּוּי", imageUrl: "/locations/fire_station.webp", roles: ["כַּבָּאי", "מְפַקֵּד", "תּוֹרַן מוֹקֵד", "מְבַקֵּר"] },
  { id: 12, name: "תַּחֲנַת מִשְׁטָרָה", imageUrl: "/locations/police_station.webp", roles: ["שׁוֹטֵר", "חוֹקֵר", "מְפַקֵּד", "אֶזְרָח"] },
  { id: 13, name: "בַּחֲוָה", imageUrl: "/locations/farm.webp", roles: ["חַקְלָאי", "רַפְתָּן", "וֶטֶרִינָר", "נֶהָג טְרַקְטוֹר"] },
  { id: 14, name: "בַּמִּסְפָּרָה", imageUrl: "/locations/barbershop.webp", roles: ["סַפָּר", "לָקוֹחַ", "עוֹזֵר סַפָּר", "פָּקִיד"] },
  { id: 15, name: "בַּסִּפְרִיָּה", imageUrl: "/locations/library.webp", roles: ["סַפְרָן", "קוֹרֵא", "תַּלְמִיד", "מוֹרֶה"] },
  { id: 16, name: "בַּמָּאפִיָּה", imageUrl: "/locations/bakery.webp", roles: ["אוֹפֶה", "מוֹכֵר", "לָקוֹחַ", "מְחַלֵּק לֶחֶם"] },
  { id: 17, name: "בַּדּוֹאַר", imageUrl: "/locations/post_office.webp", roles: ["פָּקִיד", "דַּוָּר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 18, name: "אֲתַר בְּנִיָּה", imageUrl: "/locations/construction_site.webp", roles: ["בַּנָּאי", "מְהַנְדֵּס", "נֶהָג מָנוֹף", "מְנַהֵל עֲבוֹדָה"] },
  { id: 19, name: "מַעְבָּדָה", imageUrl: "/locations/laboratory.webp", roles: ["מַדְּעָן", "פְּרוֹפֶסוֹר", "עוֹזֵר מַעְבָּדָה", "לָבוֹרַנְט"] },
  { id: 20, name: "קֶמְפִּינְג", imageUrl: "/locations/camping.webp", roles: ["מְטַיֵּל", "מַדְרִיךְ", "טַבָּח שָׂדֶה", "שׁוֹמֵר יַעַר"] },
  { id: 21, name: "בְּבֵית הַמָּלוֹן", imageUrl: "/locations/hotel.webp", roles: ["פָּקִיד קַבָּלָה", "אוֹרֵחַ", "חֲדָרָנִית", "סַבָּל"] },
  { id: 22, name: "בִּשְׂדֵה הַתְּעוּפָה", imageUrl: "/locations/airport.webp", roles: ["טַיָּס", "דַּיָּל", "נוֹסֵעַ", "בּוֹדֵק בִּטָּחוֹן"] },
  { id: 23, name: "בַּמּוּזֵאוֹן", imageUrl: "/locations/museum.webp", roles: ["מַדְרִיךְ", "שׁוֹמֵר", "מְבַקֵּר", "אוֹצֵר"] },
  { id: 24, name: "גְּלִידֶרִיָּה", imageUrl: "/locations/ice_cream_shop.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְנַהֵל", "עוֹזֵר"] },
  { id: 25, name: "בַּקִּרְקָס", imageUrl: "/locations/circus.webp", roles: ["לֵיצָן", "מְאַלֵּף", "לַהְטוּטָן", "מְנַהֵל קִרְקָס"] },
  { id: 26, name: "בַּבְּרֵכָה", imageUrl: "/locations/swimming_pool.webp", roles: ["מַצִּיל", "שַׂחְיָן", "מַדְרִיךְ שְׂחִיָּה", "לָקוֹחַ"] },
  { id: 27, name: "חֲנוּת צַעֲצוּעִים", imageUrl: "/locations/toy_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "אַבָּא", "מְסַדֵּר מַדָּפִים"] },
  { id: 28, name: "רוֹפֵא שִׁנַּיִם", imageUrl: "/locations/dentist.webp", roles: ["רוֹפֵא", "סַיַּעַת", "מְטופָּל", "מַזְכִּירָה"] },
  { id: 29, name: "תַּחֲנַת רַכֶּבֶת", imageUrl: "/locations/train_station.webp", roles: ["כַּרְטִיסָן", "נוֹסֵעַ", "נֶהָג קַטָּר", "מְנַהֵל תַּחֲנָה"] },
  { id: 30, name: "בַּמִּשְׂרָד", imageUrl: "/locations/office.webp", roles: ["מְנַהֵל", "מַזְכִּירָה", "עוֹבֵד", "לָקוֹחַ"] },
  { id: 31, name: "אוּלְפַּן חֲדָשׁוֹת", imageUrl: "/locations/news_studio.webp", roles: ["מַגִּישׁ", "צַלָּם", "מְרוּאָיין", "עוֹרֵךְ"] },
  { id: 32, name: "בַּתֵּיאַטְרוֹן", imageUrl: "/locations/theater.webp", roles: ["שַׂחְקָן", "בַּמַּאי", "מְאַפֶּרֶת", "צוֹפֶה"] },
  { id: 33, name: "בְּבֵית הַחוֹלִים", imageUrl: "/locations/hospital.webp", roles: ["רוֹפֵא", "אָח", "חוֹלֶה", "מְבַקֵּר"] },
  { id: 34, name: "תַּחֲנַת דֶּלֶק", imageUrl: "/locations/gas_station.webp", roles: ["מְתַדְּלֵק", "נֶהָג", "מוֹכֵר בַּחֲנוּת", "מְנַהֵל"] },
  { id: 35, name: "בַּבַּנְק", imageUrl: "/locations/bank.webp", roles: ["טֶלֶר", "מְנַהֵל סְנִיף", "לָקוֹחַ", "שׁוֹמֵר"] },
  { id: 36, name: "חֲנוּת חַיּוֹת", imageUrl: "/locations/pet_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "וֶטֶרִינָר", "מְסַפֵּר כְּלָבִים"] },
  { id: 37, name: "מוּסָךְ", imageUrl: "/locations/garage.webp", roles: ["מֵכָנִיקַאי", "לָקוֹחַ", "מְנַהֵל עֲבוֹדָה", "מַזְכִּירָה"] },
  { id: 38, name: "אַרְמוֹן", imageUrl: "/locations/palace.webp", roles: ["מֶלֶךְ", "מַלְכָּה", "שׁוֹמֵר", "מְשָׁרֵת"] },
  { id: 39, name: "סְפִינַת פִּירָאטִים", imageUrl: "/locations/pirate_ship.webp", roles: ["קַפִּיטָן", "מַלָּח", "טַבָּח", "תַּצְפִּיתָן"] },
  { id: 40, name: "בַּג'וּנְגֶּל", imageUrl: "/locations/jungle.webp", roles: ["חוקֵר", "מַדְרִיךְ", "צַלָּם", "מְטַיֵּל"] },
  { id: 41, name: "בַּמִּדְבָּר", imageUrl: "/locations/desert.webp", roles: ["מַדְרִיךְ", "מְטַיֵּל", "נֶהָג גִּ'יפּ", "אָרְכֵיאוֹלוֹג"] },
  { id: 42, name: "קֹטֶב צְפוֹנִי", imageUrl: "/locations/north_pole.webp", roles: ["חוקֵר", "טַיָּס", "צַלָּם", "מַדְּעָן"] },
  { id: 43, name: "צַלֶּלֶת", imageUrl: "/locations/submarine.webp", roles: ["מְפַקֵּד", "מַלָּח", "טֶכְנַאי", "מַדְּעָן"] },
  { id: 44, name: "חֲנוּת פְּרָחִים", imageUrl: "/locations/flower_shop.webp", roles: ["מוֹכֵר", "שׁוֹזֵר", "לָקוֹחַ", "מְחַלֵּק פְּרָחִים"] },
  { id: 45, name: "פִּיצֵרִיָּה", imageUrl: "/locations/pizzeria.webp", roles: ["שֵׁף פִּיצָה", "מַלְצַר", "לָקוֹחַ", "שָׁלִיחַ"] },
  { id: 46, name: "בֵּית קָפֶה", imageUrl: "/locations/cafe.webp", roles: ["בָּרִיסְטָה", "מַלְצַר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 47, name: "בֵּית מִשְׁפָּט", imageUrl: "/locations/courthouse.webp", roles: ["שׁוֹפֵט", "עוֹרֵךְ דִּין", "שׁוֹמֵר", "עֵד"] },
  { id: 48, name: "אוּלַם קוֹנְצֶרְטִים", imageUrl: "/locations/concert_hall.webp", roles: ["זַמָּר", "נַגָּן", "מְנַצֵּחַ", "מְעָרִיץ"] },
  { id: 49, name: "מִגְרַשׁ כַּדורְסַל", imageUrl: "/locations/basketball_court.webp", roles: ["שַׂחְקָן", "מְאַמֵּן", "שׁוֹפֵט", "אוֹהֵד"] },
  { id: 50, name: "מִגְרַשׁ טֶנִיס", imageUrl: "/locations/tennis_court.webp", roles: ["שַׂחְקָן", "מְאַמֵּן", "שׁוֹפֵט קַו", "אוֹסֵף כַּדּוּרִים"] },
  { id: 51, name: "חוּג קָרָאטֶה", imageUrl: "/locations/karate_class.webp", roles: ["מַדְרִיךְ", "תַּלְמִיד", "בּוֹחֵן", "הוֹרֶה"] },
  { id: 52, name: "סְטוּדְיוֹ לְבָלֶט", imageUrl: "/locations/ballet_studio.webp", roles: ["רַקְדָן", "מוֹרֶה", "נַגָּן פְּסַנְתֵּר", "תַּלְמִיד"] },
  { id: 53, name: "גָּלֶרְיַת אֳמָנוּת", imageUrl: "/locations/art_gallery.webp", roles: ["צַיָּר", "מְבַקֵּר", "אוֹצֵר", "שׁוֹמֵר"] },
  { id: 54, name: "תַּצְגוּת אופְנָה", imageUrl: "/locations/fashion_show.webp", roles: ["דּוּגְמָן", "מְעַצֵּב", "צַלָּם", "אוֹרֵחַ"] },
  { id: 55, name: "בֵּית מִרְקַחַת", imageUrl: "/locations/pharmacy.webp", roles: ["רוֹקֵחַ", "לָקוֹחַ", "עוֹזֵר רוֹקֵחַ", "מְנַהֵל"] },
  { id: 56, name: "חֲנוּת כְּלֵי עֲבוֹדָה", imageUrl: "/locations/hardware_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "סַדָּר", "מְנַהֵל"] },
  { id: 57, name: "חֲנוּת נַעֲלַיִם", imageUrl: "/locations/shoe_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְסַדֵּר", "מְנַהֵל"] },
  { id: 58, name: "חֲנוּת בְּגָדִים", imageUrl: "/locations/clothing_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְעַצֵּב", "מְסַדֵּר"] },
  { id: 59, name: "בָּאוֹטוֹבּוּס", imageUrl: "/locations/bus.webp", roles: ["נֶהָג", "נוֹסֵעַ", "מְבַקֵּר כַּרְטִיסִים", "תַּלְמִיד"] },
  { id: 60, name: "בַּמ  ּוֹנִית", imageUrl: "/locations/taxi.webp", roles: ["נֶהָג", "נוֹסֵעַ", "תַּיָּר", "שׁוֹטֵר"] },
  { id: 61, name: "רַכֶּבֶת תַּחְתִּית", imageUrl: "/locations/subway.webp", roles: ["נוֹסֵעַ", "נֶהָג", "שׁוֹמֵר", "כַּרְטִיסָן"] },
  { id: 62, name: "אֳנִיַּת תַּעֲנוּגוֹת", imageUrl: "/locations/cruise_ship.webp", roles: ["קַפִּיטָן", "נוֹסֵעַ", "מַלְצַר", "מַצִּיל"] },
  { id: 63, name: "פִּסְגַת הָהָר", imageUrl: "/locations/mountain_peak.webp", roles: ["מְטַפֵּס הָרִים", "מַדְרִיךְ", "צַלָּם", "מְחַלֵּץ"] },
  { id: 64, name: "ב  ַּמְּעָרָה", imageUrl: "/locations/cave.webp", roles: ["חוקֵר מְעָרוֹת", "אָרְכֵיאוֹלוֹג", "מַדְרִיךְ", "מְטַיֵּל"] },
  { id: 65, name: "מַפַּל מַיִם", imageUrl: "/locations/waterfall.webp", roles: ["תַּיָּר", "מַדְרִיךְ", "צַלָּם", "שׁוֹמֵר יַעַר"] },
  { id: 66, name: "בַּמַּטָּע", imageUrl: "/locations/orchard.webp", roles: ["קוֹטֵף", "חַקְלָאי", "מְנַהֵל", "נֶהָג מַשָּׂאִית"] },
  { id: 67, name: "בַּחֲמָמָה", imageUrl: "/locations/greenhouse.webp", roles: ["גַּנָּן", "מַדְּעָן", "לָקוֹחַ", "מְבַקֵּר"] },
  { id: 68, name: "בְּגַן הַיְלָדִים", imageUrl: "/locations/kindergarten.webp", roles: ["גַּנֶּנֶת", "סַיַּעַת", "יֶלֶד", "הוֹרֶה"] },
  { id: 69, name: "בָּאוּנִיבֶרְסִיטָה", imageUrl: "/locations/university.webp", roles: ["מַרְצֶה", "סְטוּדֶנְט", "חוֹקֵר", "מַזְכִּירָה"] },
  { id: 70, name: "בְּגִנַּת הַשַּׁעֲשׁוּעִים", imageUrl: "/locations/playground.webp", roles: ["יֶלֶד", "אַבָּא", "אִמָּא", "מוֹכֵר בַּלּוֹנִים"] },
  { id: 71, name: "לונָה פַּרְק", imageUrl: "/locations/amusement_park.webp", roles: ["מַפְעִיל מִתְקָנִים", "מְבַקֵּר", "שׁוֹמֵר", "מוֹכֵר כַּרְטִיסִים"] },
  { id: 72, name: "פַּרְק מַיִם", imageUrl: "/locations/water_park.webp", roles: ["מַצִּיל", "יֶלֶד", "מַדְרִיךְ", "לָקוֹחַ"] },
  { id: 73, name: "מִגְרַשׁ הַחְלָקָה", imageUrl: "/locations/skating_rink.webp", roles: ["מַחְלִיק", "מַדְרִיךְ", "מוֹכֵר כַּרְטִיסִים", "שׁוֹמֵר"] },
  { id: 74, name: "בָּאוּלִינְג", imageUrl: "/locations/bowling_alley.webp", roles: ["שַׂחְקָן", "עוֹבֵד דֶּלְפֵּק", "טֶכְנַאי", "לָקוֹחַ"] },
  { id: 75, name: "חֲנוּת מִשְׂחָקִים", imageUrl: "/locations/video_game_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "טֶכְנַאי מַחְשֵׁב", "לָקוֹחַ"] },
  { id: 76, name: "מוֹפַע קְסָמִים", imageUrl: "/locations/magic_show.webp", roles: ["קוֹסֵם", "עוֹזֵר קוֹסֵם", "מִתְנַדֵּב", "צוֹפֶה"] },
  { id: 77, name: "תֵּיאַטְרוֹן בֻּבּוֹת", imageUrl: "/locations/puppet_theater.webp", roles: ["מַפְעִיל בֻּבּוֹת", "יֶלֶד", "הוֹרֶה", "מְסַפֵּר סִפּוּרִים"] },
  { id: 78, name: "בַּחֲתֻנָּה", imageUrl: "/locations/wedding.webp", roles: ["חָתָן", "כַּלָּה", "אוֹרֵחַ", "צַלָּם"] },
  { id: 79, name: "בַּקַּרְנָבָל", imageUrl: "/locations/carnival.webp", roles: ["רַקְדָן", "נַגָּן", "מְבַקֵּר", "מוֹכֵר"] },
  { id: 80, name: "שׁוּק רְחוֹב", imageUrl: "/locations/street_market.webp", roles: ["רוֹכֵל", "לָקוֹחַ", "פַּקָּח", "סַבָּל"] },
  { id: 81, name: "מַעְבָּדַת תִּקּוּנִים", imageUrl: "/locations/repair_shop.webp", roles: ["טֶכְנַאי", "לָקוֹחַ", "מְנַהֵל", "פָּקִיד"] },
  { id: 82, name: "מֶרְכָּז מִחְזוּר", imageUrl: "/locations/recycling_center.webp", roles: ["עוֹבֵד", "נֶהָג", "אֶזְרָח", "מְנַהֵל"] },
  { id: 83, name: "תַּחֲנָה מֶטֵאוֹרוֹלוֹגִית", imageUrl: "/locations/meteorological_station.webp", roles: ["חַזַּאי", "מַדְּעָן", "צַלָּם", "מְנַהֵל"] },
  { id: 84, name: "אוּלְפַּן הַקְלָטוֹת", imageUrl: "/locations/recording_studio.webp", roles: ["זַמָּר", "טֶכְנַאי קוֹל", "מְפִיק", "נַגָּן"] },
  { id: 85, name: "סְטוּדְיוֹ לְצִלּוּם", imageUrl: "/locations/photo_studio.webp", roles: ["צַלָּם", "דּוּגְמָן", "מְאַפֶּרֶת", "לָקוֹחַ"] },
  { id: 86, name: "חֲנוּת סְפָרִים", imageUrl: "/locations/bookstore.webp", roles: ["מוֹכֵר", "קוֹרֵא", "סוֹפֵר", "מְסַדֵּר מַדָּפִים"] },
  { id: 87, name: "חֲנוּת מַחְשֵׁבִים", imageUrl: "/locations/computer_store.webp", roles: ["טֶכְנַאי", "מוֹכֵר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 88, name: "חֲנוּת מְתִיקָה", imageUrl: "/locations/candy_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "סַדָּר", "לָקוֹחַ"] },
  { id: 89, name: "חֲנוּת תַּכְשִׁיטִים", imageUrl: "/locations/jewelry_store.webp", roles: ["צוֹרֵף", "מוֹכֵר", "לָקוֹחַ", "שׁוֹמֵר"] },
  { id: 90, name: "מִפְעַל צַעֲצוּעִים", imageUrl: "/locations/toy_factory.webp", roles: ["פועֵל", "מְהַנְדֵּס", "מְעַצֵּב", "מְנַהֵל"] },
  { id: 91, name: "מִפְעַל שׁוֹקוֹלָד", imageUrl: "/locations/chocolate_factory.webp", roles: ["שׁוֹקוֹלָדְיֶר", "עוֹבֵד", "מְבַקֵּר", "מְנַהֵל"] },
  { id: 92, name: "סְטוּדְיוֹ יוֹגָה", imageUrl: "/locations/yoga_studio.webp", roles: ["מַדְרִיךְ", "מִתְרַגֵּל", "לָקוֹחַ", "מַזְכִּירָה"] },
  { id: 93, name: "מוֹעֲדוֹן שַׁחְמָט", imageUrl: "/locations/chess_club.webp", roles: ["שַׂחְקָן", "שׁוֹפֵט", "מַדְרִיךְ", "תַּלְמִיד"] },
  { id: 94, name: "מִרְפָּאַת חַיּוֹת", imageUrl: "/locations/veterinary_clinic.webp", roles: ["וֶטֶרִינָר", "אָח", "לָקוֹחַ", "מַזְכִּירָה"] },
  { id: 95, name: "בַּקִּמְפּוּס", imageUrl: "/locations/campus.webp", roles: ["מַרְצֶה", "סְטוּדֶנְט", "שׁוֹמֵר", "גַּנָּן"] },
  { id: 96, name: "חֲנוּת רָהִיטִים", imageUrl: "/locations/furniture_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מַרְכִּיב רָהִיטִים", "מְנַהֵל"] },
  { id: 97, name: "טֵלֶסְקוֹפּ עֲנָק", imageUrl: "/locations/giant_telescope.webp", roles: ["אַסְטְרוֹנוֹם", "מַדְּעָן", "מְבַקֵּר", "טֶכְנַאי"] },
  { id: 98, name: "בַּחֲצַר בֵּית הַסֵּפֶר", imageUrl: "/locations/schoolyard.webp", roles: ["מוֹרֶה תּוֹרָן", "תַּלְמִיד", "שׁוֹמֵר", "מְנַקֶּה"] },
  { id: 99, name: "מִרְפֶּסֶת תַּצְפִּית", imageUrl: "/locations/observation_deck.webp", roles: ["תַּיָּר", "מַדְרִיךְ", "צַלָּם", "שׁוֹמֵר"] },
  { id: 100, name: "מְסִבַּת סִיּוּם", imageUrl: "/locations/graduation_party.webp", roles: ["תַּלְמִיד", "הוֹרֶה", "מוֹרֶה", "מְנַהֵל"] },

  // --- 57 הסיטואציות החדשות (locations_new) ---
  { id: 101, name: "בַּיִת רָדוּף רוּחוֹת", imageUrl: "/locations_new/haunted house.webp", roles: ["רוּחַ רְפָאִים", "מְבַקֵּר מְפֹחָד", "חוֹקֵר עַל-טִבְעִי", "מַפְעִיל הַמִּתְקָן"] },
  { id: 102, name: "אֲתַר סְקִי", imageUrl: "/locations_new/ski resort.webp", roles: ["גּוֹלֵשׁ", "מַדְרִיךְ סְקִי", "מַפְעִיל רַכֶּבֶת כְּבָלִים", "מְחַלֵּץ"] },
  { id: 103, name: "סוּשִׁי בָּאר", imageUrl: "/locations_new/sushi bar.webp", roles: ["שֵׁף סוּשִׁי", "מַלְצַר", "לָקוֹחַ", "שָׁטּוֹף כֵּלִים"] },
  { id: 104, name: "קָזִינוֹ", imageUrl: "/locations_new/casino.webp", roles: ["דִּילֶר", "מְהַמֵּר", "מְאַבְטֵחַ", "מַלְצַר"] },
  { id: 105, name: "סְפָּא", imageUrl: "/locations_new/spa.webp", roles: ["מְעַסֶּה", "לָקוֹחַ", "פָּקִיד קַבָּלָה", "קוֹסְמֶטִיקָאִית"] },
  { id: 106, name: "כֶּרֶם", imageUrl: "/locations_new/vineyard.webp", roles: ["יֵינָן", "בּוֹצֵר", "תַּיָּר", "מַדְרִיךְ"] },
  { id: 107, name: "מוֹעֲדוֹן לַיְלָה", imageUrl: "/locations_new/nightclub.webp", roles: ["דִּי-גֵ'י", "בַּרְמַן", "מְאַבְטֵחַ", "בליין"] },
  { id: 108, name: "בֵּית קְבָרוֹת", imageUrl: "/locations_new/cemetery.webp", roles: ["קַבְּרָן", "אָבֵל", "שׁוֹמֵר", "מְבַקֵּר"] },
  { id: 109, name: "סָפָארִי", imageUrl: "/locations_new/safari.webp", roles: ["מַדְרִיךְ", "נֶהָג", "צַלָּם", "וֶטֶרִינָר"] },
  { id: 110, name: "אַסְדַּת נֵפְט", imageUrl: "/locations_new/oil rig.webp", roles: ["קַדָּח", "מְהַנְדֵּס", "טַבָּח", "צולְלָן טֶכְני"] },
  { id: 111, name: "סְטוּדְיוֹ לְאָמָּנוּת", imageUrl: "/locations_new/art studio.webp", roles: ["צַיָּר", "מוֹדֶל", "תַּלְמִיד", "מְבַקֵּר"] },
  { id: 112, name: "מָכוֹן כּוֹשֶׁר", imageUrl: "/locations_new/gym.webp", roles: ["מְאַמֵּן", "מִתְאַמֵּן", "פָּקִיד", "מְנַקֶּה"] },
  { id: 113, name: "פְּלָנֵטַרְיוּם", imageUrl: "/locations_new/planetarium.webp", roles: ["מַדְרִיךְ", "אַסְטְרוֹנוֹם", "מְבַקֵּר", "טֶכְנַאי"] },
  { id: 114, name: "ג  ַּן בּוֹטָנִי", imageUrl: "/locations_new/botanical garden.webp", roles: ["גַּנָּן", "בּוֹטָנַאי", "מְבַקֵּר", "צַלָּם"] },
  { id: 115, name: "בָּסִיס צְבָאִי", imageUrl: "/locations_new/military base.webp", roles: ["חַיָּל", "מְפַקֵּד", "טַבָּח", "שׁוֹמֵר"] },
  { id: 116, name: "מַרְתֵּף יַיִן", imageUrl: "/locations_new/wine cellar.webp", roles: ["סוֹמֶלְיֵה", "לָקוֹחַ", "מְנַהֵל", "עוֹבֵד"] },
  { id: 117, name: "מָטוֹס פְּרָטִי", imageUrl: "/locations_new/private jet.webp", roles: ["טַיָּס", "דַּיָּל", "אִישׁ עֲסָקִים", "מְאַבְטֵחַ"] },
  { id: 118, name: "יַאכְטָה", imageUrl: "/locations_new/yacht.webp", roles: ["סְקִיפֶּר", "מַלָּח", "טַבָּח", "אוֹרֵחַ"] },
  { id: 119, name: "מִצְרַיִם הָעַתִּיקָה", imageUrl: "/locations_new/ancient egypt.webp", roles: ["פַּרְעֹה", "עֶבֶד", "כֹּהֵן", "סוֹחֵר"] },
  { id: 120, name: "הַמַּעֲרָב הַפָּרוּעַ", imageUrl: "/locations_new/wild west town.webp", roles: ["שֶׁרִיף", "בּוֹקֵר", "פּוֹשֵׁעַ", "בַּרְמַן"] },
  { id: 121, name: "טִירה מִימֵי הַבֵּינַיִם", imageUrl: "/locations_new/medieval castle.webp", roles: ["אֲבִיר", "נָסִיךְ", "מְשָׁרֵת", "טַבָּח"] },
  { id: 122, name: "קוֹלוֹסֵיאוּם", imageUrl: "/locations_new/roman colosseum.webp", roles: ["גְּלַדְיָאטוֹר", "קֵיסָר", "צוֹפֶה", "מְאַמֵּן"] },
  { id: 123, name: "מַעְבּוֹרֶת חָלָל", imageUrl: "/locations_new/space shuttle.webp", roles: ["אַסְטְרוֹנָאוּט", "מְפַקֵּד", "מַדְּעָן", "טֶכְנַאי"] },
  { id: 124, name: "ב  ָּסִיס יָרֵחַ", imageUrl: "/locations_new/moon base.webp", roles: ["חוֹקֵר", "מְהַנְדֵּס", "מְפַקֵּד", "רוֹבּוֹטִיקַאי"] },
  { id: 125, name: "מוֹשָׁבָה עַל מַאְדִּים", imageUrl: "/locations_new/mars colony.webp", roles: ["חַקְלָאי חָלָל", "גֵּאוֹלוֹג", "מְהַנְדֵּס", "רוֹפֵא"] },
  { id: 126, name: "בּוּנְקֶר תַּת-קַרְקָעִי", imageUrl: "/locations_new/underground bunker.webp", roles: ["שׁוֹמֵר", "טֶכְנַאי", "מְפַקֵּד", "מְבַקֵּר"] },
  { id: 127, name: "אֳנִיַּת מַשָּׂא", imageUrl: "/locations_new/cargo ship.webp", roles: ["קַפִּיטָן", "מַלָּח", "מַפְעִיל מָנוֹף", "טַבָּח"] },
  { id: 128, name: "סִירַת דַּיִג", imageUrl: "/locations_new/fishing boat.webp", roles: ["דַּיָּג", "עוֹזֵר", "מַלָּח", "לָקוֹחַ"] },
  { id: 129, name: "מִגְדַּלּוֹר", imageUrl: "/locations_new/lighthouse.webp", roles: ["שׁוֹמֵר מִגְדַּלּוֹר", "מַלָּח", "תַּיָּר", "טֶכְנַאי"] },
  { id: 130, name: "מַשָּׂאִית זֶבֶל", imageUrl: "/locations_new/garbage truck.webp", roles: ["נֶהָג", "עוֹזֵר", "פַּקָּח", "מְכָנִיקַאי"] },
  { id: 131, name: "ת  ַּחֲנַת כֹּחַ גַּרְעִינִית", imageUrl: "/locations_new/nuclear power plant.webp", roles: ["מַדְּעָן", "מְהַנְדֵּס", "מְאַבְטֵחַ", "טֶכְנַאי"] },
  { id: 132, name: "סֶכֶר הִידְרוֹאֶלֶקְטְרִי", imageUrl: "/locations_new/hydroelectric dam.webp", roles: ["מְהַנְדֵּס", "טֶכְנַאי", "שׁוֹמֵר", "מְבַקֵּר"] },
  { id: 133, name: "חַוַּת טוּרְבִּינוֹת רוּחַ", imageUrl: "/locations_new/wind farm.webp", roles: ["טֶכְנַאי", "מְהַנְדֵּס", "חַקְלָאי", "מְבַקֵּר"] },
  { id: 134, name: "חַוָּה סוֹלָרִית", imageUrl: "/locations_new/solar farm.webp", roles: ["מַתְקִין", "טֶכְנַאי", "מְנַהֵל", "פַּקָּח"] },
  { id: 135, name: "חֲדַר שָׁרָתִים", imageUrl: "/locations_new/server room.webp", roles: ["אִישׁ מַחְשֵׁב", "טֶכְנַאי", "מְנַהֵל רֶשֶׁת", "מְאַבְטֵחַ"] },
  { id: 136, name: "מִפְעַל מְכוֹנִיּוֹת", imageUrl: "/locations_new/car factory.webp", roles: ["עוֹבֵד פַּס יִיצוּר", "רוֹבּוֹטִיקַאי", "מְהַנְדֵּס", "בּוֹחֵן"] },
  { id: 137, name: "מִכְרֵה פֶּחָם", imageUrl: "/locations_new/coal mine.webp", roles: ["כּוֹרֶה", "מְהַנְדֵּס", "מְפַקֵּחַ", "נֶהָג קָרוֹנִית"] },
  { id: 138, name: "מִכְרֵה זָהָב", imageUrl: "/locations_new/gold mine.webp", roles: ["כּוֹרֶה", "גֵּאוֹלוֹג", "שׁוֹמֵר", "מְנַהֵל"] },
  { id: 139, name: "מִכְרֵה יַהֲלוֹמִים", imageUrl: "/locations_new/diamond mine.webp", roles: ["כּוֹרֶה", "מוּמְחֶה יַהֲלוֹמִים", "מְאַבְטֵחַ", "מַדְּעָן"] },
  { id: 140, name: "מַחְצֵבָה", imageUrl: "/locations_new/quarry.webp", roles: ["פּוֹעֵל", "נֶהָג דַּחְפּוֹר", "מְפוֹצֵץ", "מְהַנְדֵּס"] },
  { id: 141, name: "מַחְסַן עֵצִים", imageUrl: "/locations_new/lumber yard.webp", roles: ["נַגָּר", "מוֹכֵר", "לָקוֹחַ", "מַלְגְזָן"] },
  { id: 142, name: "אַקְוַרְיוּם", imageUrl: "/locations_new/aquarium.webp", roles: ["צולְלָן", "מְטַפֵּל", "מְבַקֵּר", "מַדְּעָן"] },
  { id: 143, name: "מוּזֵאוֹן הַמ  ַּדָּע", imageUrl: "/locations_new/science museum.webp", roles: ["מַדְּעָן", "מַדְרִיךְ", "יֶלֶד", "מְבַקֵּר"] },
  { id: 144, name: "מוּזֵאוֹן שַׁעֲוָה", imageUrl: "/locations_new/wax museum.webp", roles: ["פַּסָּל", "מְבַקֵּר", "שׁוֹמֵר", "צַלָּם"] },
  { id: 145, name: "בֵּית אוֹפֵּרָה", imageUrl: "/locations_new/opera house.webp", roles: ["זַמָּר", "נַגָּן", "מְנַצֵּחַ", "צוֹפֶה"] },
  { id: 146, name: "סַדְנַת בִּשּׁוּל", imageUrl: "/locations_new/cooking class.webp", roles: ["שֵׁף", "תַּלְמִיד", "טועֵם", "מַדְרִיךְ"] },
  { id: 147, name: "סַדְנַת קֵרָמִיקָה", imageUrl: "/locations_new/pottery class.webp", roles: ["אֳמָן", "תַּלְמִיד", "מַדְרִיךְ", "מְבַקֵּר"] },
  { id: 148, name: "חוּג צִיּוּר", imageUrl: "/locations_new/painting class.webp", roles: ["מוֹרֶה", "תַּלְמִיד", "מוֹדֶל", "צַיָּר"] },
  { id: 149, name: "סַדְנַת צִלּוּם", imageUrl: "/locations_new/photography workshop.webp", roles: ["צַלָּם", "מַדְרִיךְ", "דּוּגְמָן", "תַּלְמִיד"] },
  { id: 150, name: "טוּרְנִיר שַׁחְמָט", imageUrl: "/locations_new/chess tournament.webp", roles: ["שַׂחְקָן", "שׁוֹפֵט", "מְאַמֵּן", "צוֹפֶה"] },
  { id: 151, name: "טוּרְנִיר פּוֹקֶר", imageUrl: "/locations_new/poker tournament.webp", roles: ["שַׂחְקָן", "דִּילֶר", "מְלַקֵּט", "צוֹפֶה"] },
  { id: 152, name: "מָרָתוֹן", imageUrl: "/locations_new/marathon.webp", roles: ["רָץ", "סַדָּר", "חַלְקַן מַיִם", "חוֹבֵשׁ"] },
  { id: 153, name: "טְרִיאַתְלוֹן", imageUrl: "/locations_new/triathlon.webp", roles: ["סְפּוֹרְטַאי", "מְאַמֵּן", "שׁוֹפֵט", "מְחַלֵּץ"] },
  { id: 154, name: "מֵרוֹץ אוֹפַנַּיִם", imageUrl: "/locations_new/cycling race.webp", roles: ["רוֹכֵב", "מְכָנִיקַאי", "נֶהָג לִוּוּי", "אוֹהֵד"] },
  { id: 155, name: "מֵרוֹץ סוּסִים", imageUrl: "/locations_new/horse race.webp", roles: ["גּ'וֹקִי", "מְהַמֵּר", "מְאַמֵּן", "סַדָּר"] },
  { id: 156, name: "מֵרוֹץ מְכוֹנִיּוֹת", imageUrl: "/locations_new/car race.webp", roles: ["נֶהָג", "מְכָנִיקַאי", "מַנְחֶה", "אוֹהֵד"] },
  { id: 157, name: "תַּעֲרוּכַת כְּלָבִים", imageUrl: "/locations_new/dog show.webp", roles: ["מַצִּיג", "שׁוֹפֵט", "וֶטֶרִינָר", "מְבַקֵּר"] },
  { id: 158, name: "תַּעֲרוּכַת רֶכֶב", imageUrl: "/locations_new/auto show.webp", roles: ["מוֹכֵר", "דּוּגְמָן", "לָקוֹחַ", "עִתּוֹנַאי"] }
];