export interface Situation {
  id: number;
  name: string;
  imageUrl: string;
  roles: string[];
}

export const situations: Situation[] = [
  { id: 1, name: "בַּסּוּפֶּרְמַרְקֶט", imageUrl: "/locations/supermarket.webp", roles: ["קוֹפַאי", "לָקוֹחַ", "סַדָּר", "מְנַהֵל"] },
  { id: 2, name: "גַּן חַיּוֹת", imageUrl: "/locations/zoo.webp", roles: ["מְטַפֵּל", "וֶטֶרִינָר", "מְבַקֵּר", "שׁוֹמֵר"] },
  { id: 3, name: "מְסִבַּת יוֹמֻלֶּדֶת", imageUrl: "/locations/birthday_party.webp", roles: ["יֶלֶד יוֹמֻלֶּדֶת", "קוֹסֵם", "חָבֵר", "לֵיצָן"] },
  { id: 4, name: "מַעֲמַקֵּי הַיָּם", imageUrl: "/locations/deep_sea.webp", roles: ["צַלָּן", "מַדְּעָן", "נֶהָג צַלֶּלֶת", "צַלָּם"] },
  { id: 5, name: "תַּחֲנַת חָלָל", imageUrl: "/locations/space_station.webp", roles: ["אַסְטְרוֹנָאוּט", "מְפַקֵּד", "מַדְּעָן", "טֶכְנַאי"] },
  { id: 6, name: "בַּמִּרְפָּאָה", imageUrl: "/locations/clinic.webp", roles: ["רוֹפֵא", "חוֹלֶה", "אָחוֹת", "מַזְכִּירָה"] },
  { id: 7, name: "בַּקּוֹלְנוֹעַ", imageUrl: "/locations/cinema.webp", roles: ["סַדָּר", "צוֹפה", "מוֹכֵר פּוֹפְּקוֹרְן", "מַקְרִין"] },
  { id: 8, name: "בַּגִּנָּה הַצִּבּוּרִית", imageUrl: "/locations/public_park.webp", roles: ["יֶלֶד", "הַדּוֹדָה", "סָבְתָא", "שׁוֹמֵר"] },
  { id: 9, name: "בַּמִּטְבָּח", imageUrl: "/locations/kitchen.webp", roles: ["טַבָּח", "עוֹזֵר טַבָּח", "מַלְצַר", "שׁוֹטֵף כֵּלִים"] },
  { id: 10, name: "מִגְרַשׁ כַּדּוּרֶגֶל", imageUrl: "/locations/soccer_field.webp", roles: ["שַׂחְקָן", "שׁוֹפֵט", "מְאַמֵּן", "אוֹהֵד"] },
  { id: 11, name: "תַּחֲנַת כִּבּוּי", imageUrl: "/locations/fire_station.webp", roles: ["כַּבָּאי", "מְפַקֵּד", "תּוֹרַן מוֹקֵד", "מְבַקֵּר"] },
  { id: 12, name: "תַּחֲנַת מִשְׁטָרָה", imageUrl: "/locations/police_station.webp", roles: ["שׁוֹטֵר", "חוֹקֵר", "מְפַקֵּד", "אֶזְרָח"] },
  { id: 13, name: "בַּחֲוָה", imageUrl: "/locations/farm.webp", roles: ["חַקְלָאי", "רַפְתָּן", "וֶטֶרִינָר", "נֶהָג טְרַקְטוֹר"] },
  { id: 14, name: "בַּמִּסְפָּרָה", imageUrl: "/locations/barbershop.webp", roles: ["סַפָּר", "לָקוֹחַ", "עוֹזֵר סַפָּר", "פָּקִיד"] },
  { id: 15, name: "בַּסִּפְרִיָּה", imageUrl: "/locations/library.webp", roles: ["סַפְרָן", "קוֹרֵא", "תַּלְמִיד", "מוֹרֶה"] },
  { id: 16, name: "בַּמָּאפִיָּה", imageUrl: "/locations/bakery.webp", roles: ["אוֹפֶה", "מוֹכֵר", "לָקוֹחַ", "מְחַלֵּק לֶחֶם"] },
  { id: 17, name: "בַּדּוֹאַר", imageUrl: "/locations/post_office.webp", roles: ["פָּקִיד", "דַּוָּר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 18, name: "אֲתַר בְּנִיָּה", imageUrl: "/locations/construction_site.webp", roles: ["בַּנָּאי", "מְהַנְדֵּס", "נֶהָג מָנוֹף", "מְנַהֵל עֲבוֹדָה"] },
  { id: 19, name: "מַעְבָּדָה", imageUrl: "/locations/laboratory.webp", roles: ["מַדְּעָן", "פְּרוֹפֶסוֹר", "עוֹזֵר מַעְבָּדָה", "לָבוֹרַנְט"] },
  { id: 20, name: "קֶמְפִּינְג", imageUrl: "/locations/camping.webp", roles: ["מְטַיֵּל", "מַדְרִיךְ", "טַבָּח שָׂדֶה", "שׁוֹמֵר יַעַר"] },
  { id: 21, name: "בְּבֵית הַמָּלוֹן", imageUrl: "/locations/hotel.webp", roles: ["פָּקִיד קַבָּלָה", "אוֹרֵחַ", "חֲדָרָנִית", "סַבָּל"] },
  { id: 22, name: "בִּשְׂדֵה הַתְּעוּפָה", imageUrl: "/locations/airport.webp", roles: ["טַיָּס", "דַּיָּל", "נוֹסֵעַ", "בּוֹדֵק בִּטָּחוֹן"] },
  { id: 23, name: "בַּמּוּזֵאוֹן", imageUrl: "/locations/museum.webp", roles: ["מַדְרִיךְ", "שׁוֹמֵר", "מְבַקֵּר", "אוֹצֵר"] },
  { id: 24, name: "גְּלִידֶרִיָּה", imageUrl: "/locations/ice_cream_shop.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְנַהֵל", "עוֹזֵר"] },
  { id: 25, name: "בַּקִּרְקָס", imageUrl: "/locations/circus.webp", roles: ["לֵיצָן", "מְאַלֵּף", "לַהְטוּטָן", "מְנַהֵל קִרְקָס"] },
  { id: 26, name: "בַּבְּרֵכָה", imageUrl: "/locations/swimming_pool.webp", roles: ["מַצִּיל", "שַׂחְיָן", "מַדְרִיךְ שְׂחִיָּה", "לָקוֹחַ"] },
  { id: 27, name: "חֲנוּת צַעֲצוּעִים", imageUrl: "/locations/toy_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "אַבָּא", "מְסַדֵּר מַדָּפִים"] },
  { id: 28, name: "רוֹפֵא שִׁנַּיִם", imageUrl: "/locations/dentist.webp", roles: ["רוֹפֵא", "סַיַּעַת", "מְטופָּל", "מַזְכִּירָה"] },
  { id: 29, name: "תַּחֲנַת רַכֶּבֶת", imageUrl: "/locations/train_station.webp", roles: ["כַּרְטִיסָן", "נוֹסֵעַ", "נֶהָג קַטָּר", "מְנַהֵל תַּחֲנָה"] },
  { id: 30, name: "בַּמִּשְׂרָד", imageUrl: "/locations/office.webp", roles: ["מְנַהֵל", "מַזְכִּירָה", "עוֹבֵד", "לָקוֹחַ"] },
  { id: 31, name: "אוּלְפַּן חֲדָשׁוֹת", imageUrl: "/locations/news_studio.webp", roles: ["מַגִּישׁ", "צַלָּם", "מְרוּאָיין", "עוֹרֵךְ"] },
  { id: 32, name: "בַּתֵּיאַטְרוֹן", imageUrl: "/locations/theater.webp", roles: ["שַׂחְקָן", "בַּמַּאי", "מְאַפֶּרֶת", "צוֹפֶה"] },
  { id: 33, name: "בְּבֵית הַחוֹלִים", imageUrl: "/locations/hospital.webp", roles: ["רוֹפֵא", "אָח", "חוֹלֶה", "מְבַקֵּר"] },
  { id: 34, name: "תַּחֲנַת דֶּלֶק", imageUrl: "/locations/gas_station.webp", roles: ["מְתַדְּלֵק", "נֶהָג", "מוֹכֵר בַּחֲנוּת", "מְנַהֵל"] },
  { id: 35, name: "בַּבַּנְק", imageUrl: "/locations/bank.webp", roles: ["טֶלֶר", "מְנַהֵל סְנִיף", "לָקוֹחַ", "שׁוֹמֵר"] },
  { id: 36, name: "חֲנוּת חַיּוֹת", imageUrl: "/locations/pet_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "וֶטֶרִינָר", "מְסַפֵּר כְּלָבִים"] },
  { id: 37, name: "מוּסָךְ", imageUrl: "/locations/garage.webp", roles: ["מֵכָנִיקַאי", "לָקוֹחַ", "מְנַהֵל עֲבוֹדָה", "מַזְכִּירָה"] },
  { id: 38, name: "אַרְמוֹן", imageUrl: "/locations/palace.webp", roles: ["מֶלֶךְ", "מַלְכָּה", "שׁוֹמֵר", "מְשָׁרֵת"] },
  { id: 39, name: "סְפִינַת פִּירָאטִים", imageUrl: "/locations/pirate_ship.webp", roles: ["קַפִּיטָן", "מַלָּח", "טַבָּח", "תַּצְפִּיתָן"] },
  { id: 40, name: "בַּג'וּנְגֶּל", imageUrl: "/locations/jungle.webp", roles: ["חוקֵר", "מַדְרִיךְ", "צַלָּם", "מְטַיֵּל"] },
  { id: 41, name: "בַּמִּדְבָּר", imageUrl: "/locations/desert.webp", roles: ["מַדְרִיךְ", "מְטַיֵּל", "נֶהָג גִּ'יפּ", "אָרְכֵיאוֹלוֹג"] },
  { id: 42, name: "קֹטֶב צְפוֹנִי", imageUrl: "/locations/north_pole.webp", roles: ["חוקֵר", "טַיָּס", "צַלָּם", "מַדְּעָן"] },
  { id: 43, name: "צַלֶּלֶת", imageUrl: "/locations/submarine.webp", roles: ["מְפַקֵּד", "מַלָּח", "טֶכְנַאי", "מַדְּעָן"] },
  { id: 44, name: "חֲנוּת פְּרָחִים", imageUrl: "/locations/flower_shop.webp", roles: ["מוֹכֵר", "שׁוֹזֵר", "לָקוֹחַ", "מְחַלֵּק פְּרָחִים"] },
  { id: 45, name: "פִּיצֵרִיָּה", imageUrl: "/locations/pizzeria.webp", roles: ["שֵׁף פִּיצָה", "מַלְצַר", "לָקוֹחַ", "שָׁלִיחַ"] },
  { id: 46, name: "בֵּית קָפֶה", imageUrl: "/locations/cafe.webp", roles: ["בָּרִיסְטָה", "מַלְצַר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 47, name: "בֵּית מִשְׁפָּט", imageUrl: "/locations/courthouse.webp", roles: ["שׁוֹפֵט", "עוֹרֵךְ דִּין", "שׁוֹמֵר", "עֵד"] },
  { id: 48, name: "אוּלַם קוֹנְצֶרְטִים", imageUrl: "/locations/concert_hall.webp", roles: ["זַמָּר", "נַגָּן", "מְנַצֵּחַ", "מְעָרִיץ"] },
  { id: 49, name: "מִגְרַשׁ כַּדורְסַל", imageUrl: "/locations/basketball_court.webp", roles: ["שַׂחְקָן", "מְאַמֵּן", "שׁוֹפֵט", "אוֹהֵד"] },
  { id: 50, name: "מִגְרַשׁ טֶנִיס", imageUrl: "/locations/tennis_court.webp", roles: ["שַׂחְקָן", "מְאַמֵּן", "שׁוֹפֵט קַו", "אוֹסֵף כַּדּוּרִים"] },
  { id: 51, name: "חוּג קָרָאטֶה", imageUrl: "/locations/karate_class.webp", roles: ["מַדְרִיךְ", "תַּלְמִיד", "בּוֹחֵן", "הוֹרֶה"] },
  { id: 52, name: "סְטוּדְיוֹ לְבָלֶט", imageUrl: "/locations/ballet_studio.webp", roles: ["רַקְדָן", "מוֹרֶה", "נַגָּן פְּסַנְתֵּר", "תַּלְמִיד"] },
  { id: 53, name: "גָּלֶרְיַת אֳמָנוּת", imageUrl: "/locations/art_gallery.webp", roles: ["צַיָּר", "מְבַקֵּר", "אוֹצֵר", "שׁוֹמֵר"] },
  { id: 54, name: "תַּצְגוּת אופְנָה", imageUrl: "/locations/fashion_show.webp", roles: ["דּוּגְמָן", "מְעַצֵּב", "צַלָּם", "אוֹרֵחַ"] },
  { id: 55, name: "בֵּית מִרְקַחַת", imageUrl: "/locations/pharmacy.webp", roles: ["רוֹקֵחַ", "לָקוֹחַ", "עוֹזֵר רוֹקֵחַ", "מְנַהֵל"] },
  { id: 56, name: "חֲנוּת כְּלֵי עֲבוֹדָה", imageUrl: "/locations/hardware_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "סַדָּר", "מְנַהֵל"] },
  { id: 57, name: "חֲנוּת נַעֲלַיִם", imageUrl: "/locations/shoe_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְסַדֵּר", "מְנַהֵל"] },
  { id: 58, name: "חֲנוּת בְּגָדִים", imageUrl: "/locations/clothing_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מְעַצֵּב", "מְסַדֵּר"] },
  { id: 59, name: "בָּאוֹטוֹבּוּס", imageUrl: "/locations/bus.webp", roles: ["נֶהָג", "נוֹסֵעַ", "מְבַקֵּר כַּרְטִיסִים", "תַּלְמִיד"] },
  { id: 60, name: "בַּמּוֹנִית", imageUrl: "/locations/taxi.webp", roles: ["נֶהָג", "נוֹסֵעַ", "תַּיָּר", "שׁוֹטֵר"] },
  { id: 61, name: "רַכֶּבֶת תַּחְתִּית", imageUrl: "/locations/subway.webp", roles: ["נוֹסֵעַ", "נֶהָג", "שׁוֹמֵר", "כַּרְטִיסָן"] },
  { id: 62, name: "אֳנִיַּת תַּעֲנוּגוֹת", imageUrl: "/locations/cruise_ship.webp", roles: ["קַפִּיטָן", "נוֹסֵעַ", "מַלְצַר", "מַצִּיל"] },
  { id: 63, name: "פִּסְגַת הָהָר", imageUrl: "/locations/mountain_peak.webp", roles: ["מְטַפֵּס הָרִים", "מַדְרִיךְ", "צַלָּם", "מְחַלֵּץ"] },
  { id: 64, name: "בַּמְּעָרָה", imageUrl: "/locations/cave.webp", roles: ["חוקֵר מְעָרוֹת", "אָרְכֵיאוֹלוֹג", "מַדְרִיךְ", "מְטַיֵּל"] },
  { id: 65, name: "מַפַּל מַיִם", imageUrl: "/locations/waterfall.webp", roles: ["תַּיָּר", "מַדְרִיךְ", "צַלָּם", "שׁוֹמֵר יַעַר"] },
  { id: 66, name: "בַּמַּטָּע", imageUrl: "/locations/orchard.webp", roles: ["קוֹטֵף", "חַקְלָאי", "מְנַהֵל", "נֶהָג מַשָּׂאִית"] },
  { id: 67, name: "בַּחֲמָמָה", imageUrl: "/locations/greenhouse.webp", roles: ["גַּנָּן", "מַדְּעָן", "לָקוֹחַ", "מְבַקֵּר"] },
  { id: 68, name: "בְּגַן הַיְלָדִים", imageUrl: "/locations/kindergarten.webp", roles: ["גַּנֶּנֶת", "סַיַּעַת", "יֶלֶד", "הוֹרֶה"] },
  { id: 69, name: "בָּאוּנִיבֶרְסִיטָה", imageUrl: "/locations/university.webp", roles: ["מַרְצֶה", "סְטוּדֶנְט", "חוֹקֵר", "מַזְכִּירָה"] },
  { id: 70, name: "בְּגִנַּת הַשַּׁעֲשׁוּעִים", imageUrl: "/locations/playground.webp", roles: ["יֶלֶד", "אַבָּא", "אִמָּא", "מוֹכֵר בַּלּוֹנִים"] },
  { id: 71, name: "לונָה פַּרְק", imageUrl: "/locations/amusement_park.webp", roles: ["מַפְעִיל מִתְקָנִים", "מְבַקֵּר", "שׁוֹמֵר", "מוֹכֵר כַּרְטִיסִים"] },
  { id: 72, name: "פַּרְק מַיִם", imageUrl: "/locations/water_park.webp", roles: ["מַצִּיל", "יֶלֶד", "מַדְרִיךְ", "לָקוֹחַ"] },
  { id: 73, name: "מִגְרַשׁ הַחְלָקָה", imageUrl: "/locations/skating_rink.webp", roles: ["מַחְלִיק", "מַדְרִיךְ", "מוֹכֵר כַּרְטִיסִים", "שׁוֹמֵר"] },
  { id: 74, name: "בָּאוּלִינְג", imageUrl: "/locations/bowling_alley.webp", roles: ["שַׂחְקָן", "עוֹבֵד דֶּלְפֵּק", "טֶכְנַאי", "לָקוֹחַ"] },
  { id: 75, name: "חֲנוּת מִשְׂחָקִים", imageUrl: "/locations/video_game_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "טֶכְנַאי מַחְשֵׁב", "לָקוֹחַ"] },
  { id: 76, name: "מוֹפַע קְסָמִים", imageUrl: "/locations/magic_show.webp", roles: ["קוֹסֵם", "עוֹזֵר קוֹסֵם", "מִתְנַדֵּב", "צוֹפֶה"] },
  { id: 77, name: "תֵּיאַטְרוֹן בֻּבּוֹת", imageUrl: "/locations/puppet_theater.webp", roles: ["מַפְעִיל בֻּבּוֹת", "יֶלֶד", "הוֹרֶה", "מְסַפֵּר סִפּוּרִים"] },
  { id: 78, name: "בַּחֲתֻנָּה", imageUrl: "/locations/wedding.webp", roles: ["חָתָן", "כַּלָּה", "אוֹרֵחַ", "צַלָּם"] },
  { id: 79, name: "בַּקַּרְנָבָל", imageUrl: "/locations/carnival.webp", roles: ["רַקְדָן", "נַגָּן", "מְבַקֵּר", "מוֹכֵר"] },
  { id: 80, name: "שׁוּק רְחוֹב", imageUrl: "/locations/street_market.webp", roles: ["רוֹכֵל", "לָקוֹחַ", "פַּקָּח", "סַבָּל"] },
  { id: 81, name: "מַעְבָּדַת תִּקּוּנִים", imageUrl: "/locations/repair_shop.webp", roles: ["טֶכְנַאי", "לָקוֹחַ", "מְנַהֵל", "פָּקִיד"] },
  { id: 82, name: "מֶרְכָּז מִחְזוּר", imageUrl: "/locations/recycling_center.webp", roles: ["עוֹבֵד", "נֶהָג", "אֶזְרָח", "מְנַהֵל"] },
  { id: 83, name: "תַּחֲנָה מֶטֵאוֹרוֹלוֹגִית", imageUrl: "/locations/meteorological_station.webp", roles: ["חַזַּאי", "מַדְּעָן", "צַלָּם", "מְנַהֵל"] },
  { id: 84, name: "אוּלְפַּן הַקְלָטוֹת", imageUrl: "/locations/recording_studio.webp", roles: ["זַמָּר", "טֶכְנַאי קוֹל", "מְפִיק", "נַגָּן"] },
  { id: 85, name: "סְטוּדְיוֹ לְצִלּוּם", imageUrl: "/locations/photo_studio.webp", roles: ["צַלָּם", "דּוּגְמָן", "מְאַפֶּרֶת", "לָקוֹחַ"] },
  { id: 86, name: "חֲנוּת סְפָרִים", imageUrl: "/locations/bookstore.webp", roles: ["מוֹכֵר", "קוֹרֵא", "סוֹפֵר", "מְסַדֵּר מַדָּפִים"] },
  { id: 87, name: "חֲנוּת מַחְשֵׁבִים", imageUrl: "/locations/computer_store.webp", roles: ["טֶכְנַאי", "מוֹכֵר", "לָקוֹחַ", "מְנַהֵל"] },
  { id: 88, name: "חֲנוּת מְתִיקָה", imageUrl: "/locations/candy_store.webp", roles: ["מוֹכֵר", "יֶלֶד", "סַדָּר", "לָקוֹחַ"] },
  { id: 89, name: "חֲנוּת תַּכְשִׁיטִים", imageUrl: "/locations/jewelry_store.webp", roles: ["צוֹרֵף", "מוֹכֵר", "לָקוֹחַ", "שׁוֹמֵר"] },
  { id: 90, name: "מִפְעַל צַעֲצוּעִים", imageUrl: "/locations/toy_factory.webp", roles: ["פועֵל", "מְהַנְדֵּס", "מְעַצֵּב", "מְנַהֵל"] },
  { id: 91, name: "מִפְעַל שׁוֹקוֹלָד", imageUrl: "/locations/chocolate_factory.webp", roles: ["שׁוֹקוֹלָדְיֶר", "עוֹבֵד", "מְבַקֵּר", "מְנַהֵל"] },
  { id: 92, name: "סְטוּדְיוֹ יוֹגָה", imageUrl: "/locations/yoga_studio.webp", roles: ["מַדְרִיךְ", "מִתְרַגֵּל", "לָקוֹחַ", "מַזְכִּירָה"] },
  { id: 93, name: "מוֹעֲדוֹן שַׁחְמָט", imageUrl: "/locations/chess_club.webp", roles: ["שַׂחְקָן", "שׁוֹפֵט", "מַדְרִיךְ", "תַּלְמִיד"] },
  { id: 94, name: "מִרְפָּאַת חַיּוֹת", imageUrl: "/locations/veterinary_clinic.webp", roles: ["וֶטֶרִינָר", "אָח", "לָקוֹחַ", "מַזְכִּירָה"] },
  { id: 95, name: "בַּקִּמְפּוּס", imageUrl: "/locations/campus.webp", roles: ["מַרְצֶה", "סְטוּדֶנְט", "שׁוֹמֵר", "גַּנָּן"] },
  { id: 96, name: "חֲנוּת רָהִיטִים", imageUrl: "/locations/furniture_store.webp", roles: ["מוֹכֵר", "לָקוֹחַ", "מַרְכִּיב רָהִיטִים", "מְנַהֵל"] },
  { id: 97, name: "טֵלֶסְקוֹפּ עֲנָק", imageUrl: "/locations/giant_telescope.webp", roles: ["אַסְטְרוֹנוֹם", "מַדְּעָן", "מְבַקֵּר", "טֶכְנַאי"] },
  { id: 98, name: "בַּחֲצַר בֵּית הַסֵּפֶר", imageUrl: "/locations/schoolyard.webp", roles: ["מוֹרֶה תּוֹרָן", "תַּלְמִיד", "שׁוֹמֵר", "מְנַקֶּה"] },
  { id: 99, name: "מִרְפֶּסֶת תַּצְפִּית", imageUrl: "/locations/observation_deck.webp", roles: ["תַּיָּר", "מַדְרִיךְ", "צַלָּם", "שׁוֹמֵר"] },
  { id: 100, name: "מְסִבַּת סִיּוּם", imageUrl: "/locations/graduation_party.webp", roles: ["תַּלְמִיד", "הוֹרֶה", "מוֹרֶה", "מְנַהֵל"] }
];